<?php return array (
  0 => 
  array (
    'name' => 'm3',
    'nick' => '主持人3',
    'score' => '60',
    'url' => '0',
  ),
  1 => 
  array (
    'name' => 'm1',
    'nick' => '主持人1',
    'score' => '30',
    'url' => 'http://admin.soso.com/img//moderator/81466685077e777f2497.png',
  ),
  2 => 
  array (
    'name' => 'm2',
    'nick' => '主持人2',
    'score' => '20',
    'url' => 'http://admin.soso.com/img//moderator/5820161865078cd02e11e5.png',
  ),
);