<?php return array (
  1 => 
  array (
    'id' => '1',
    'name' => '鲜花',
    'url' => 'http://admin.soso.com/img//propinfo/1.jpg',
    'score' => '10',
  ),
  2 => 
  array (
    'id' => '2',
    'name' => '红玫瑰',
    'url' => 'http://admin.soso.com/img//propinfo/2.jpg',
    'score' => '20',
  ),
  3 => 
  array (
    'id' => '3',
    'name' => '蓝玫瑰',
    'url' => 'http://admin.soso.com/img//propinfo/3.jpg',
    'score' => '30',
  ),
  4 => 
  array (
    'id' => '4',
    'name' => '幸运花',
    'url' => 'http://admin.soso.com/img//propinfo/4.jpg',
    'score' => '40',
  ),
  5 => 
  array (
    'id' => '5',
    'name' => '幸运棒棒糖',
    'url' => 'http://admin.soso.com/img//propinfo/5.jpg',
    'score' => '50',
  ),
  6 => 
  array (
    'id' => '6',
    'name' => '幸运丘比特',
    'url' => 'http://admin.soso.com/img//propinfo/6.jpg',
    'score' => '60',
  ),
  7 => 
  array (
    'id' => '7',
    'name' => '鼓掌',
    'url' => 'http://admin.soso.com/img//propinfo/7.jpg',
    'score' => '20',
  ),
  8 => 
  array (
    'id' => '8',
    'name' => '仙侠世界徽章',
    'url' => 'http://admin.soso.com/img//propinfo/8.jpg',
    'score' => '30',
  ),
  9 => 
  array (
    'id' => '9',
    'name' => '玫瑰之约',
    'url' => 'http://admin.soso.com/img//propinfo/9.jpg',
    'score' => '50',
  ),
  10 => 
  array (
    'id' => '10',
    'name' => '甜蜜蜜',
    'url' => 'http://admin.soso.com/img//propinfo/10.jpg',
    'score' => '80',
  ),
  11 => 
  array (
    'id' => '11',
    'name' => '亲亲',
    'url' => 'http://admin.soso.com/img//propinfo/11.jpg',
    'score' => '100',
  ),
  12 => 
  array (
    'id' => '12',
    'name' => '爱情契约',
    'url' => 'http://admin.soso.com/img//propinfo/12.jpg',
    'score' => '100',
  ),
  13 => 
  array (
    'id' => '13',
    'name' => '豪宅',
    'url' => 'http://admin.soso.com/img//propinfo/13.jpg',
    'score' => '200',
  ),
  14 => 
  array (
    'id' => '14',
    'name' => '玫瑰花园',
    'url' => 'http://admin.soso.com/img//propinfo/14.jpg',
    'score' => '200',
  ),
  15 => 
  array (
    'id' => '15',
    'name' => '红包',
    'url' => 'http://admin.soso.com/img//propinfo/15.jpg',
    'score' => '200',
  ),
  16 => 
  array (
    'id' => '16',
    'name' => '丘比特之箭',
    'url' => 'http://admin.soso.com/img//propinfo/16.jpg',
    'score' => '100',
  ),
);