<?php return array (
  0 => 
  array (
    'uid' => '111',
    'privilege' => '0',
    'time' => '2012-10-14 23:26:23',
    'score' => '300',
    'face_id' => '0',
    'level' => '0',
    'nick' => '111',
    'area' => '',
  ),
  1 => 
  array (
    'uid' => '333',
    'privilege' => '0',
    'time' => '2012-10-15 08:39:55',
    'score' => '200',
    'face_id' => '0',
    'level' => '0',
    'nick' => '333',
    'area' => '地庙',
  ),
  2 => 
  array (
    'uid' => '222',
    'privilege' => '0',
    'time' => '2012-10-15 08:39:55',
    'score' => '11',
    'face_id' => '0',
    'level' => '0',
    'nick' => '222',
    'area' => '天塔',
  ),
);